#!/usr/bin/env bash
# Script that configures a new Ubuntu machine to Install nginx
# Nginx should be listening on port 80
# When querying Nginx at its root / with a GET request (requesting a page)
# using curl, it must return a page that contains the string Hello World!

sudo apt update
sudo apt installi -y nginx
sudo ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/http/index.html
sudo service nginx start
